# Generated by SQL Server Management Studio at 11:38 PM on 2018-08-30

Import-Module SqlServer
# Set up connection and database SMO objects

$password = "<replace with your password>"
$sqlConnectionString = "Data Source=aderbal.database.windows.net;Initial Catalog=MyAddressBookPlus;User ID=aderbaladmin;Password=$password;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False;Packet Size=4096;Application Name=`"Microsoft SQL Server Management Studio`""
$smoDatabase = Get-SqlDatabase -ConnectionString $sqlConnectionString

# If your encryption changes involve keys in Azure Key Vault, uncomment one of the lines below in order to authenticate:
#   * Prompt for a username and password:
#Add-SqlAzureAuthenticationContext -Interactive

#   * Enter a Client ID, Secret, and Tenant ID:
#Add-SqlAzureAuthenticationContext -ClientID '<Client ID>' -Secret '<Secret>' -Tenant '<Tenant ID>'

# Change encryption schema

$encryptionChanges = @()

# Add changes for table [dbo].[Contact]
$encryptionChanges += New-SqlColumnEncryptionSettings -ColumnName dbo.Contact.SIN_Number -EncryptionType Randomized -EncryptionKey "CEK_Auto1"

Set-SqlColumnEncryption -ColumnEncryptionSettings $encryptionChanges -InputObject $smoDatabase

